version: '3.6'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: configuration.env
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    env_file: configuration.env
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    env_file: configuration.env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file: configuration.env
    working_dir: /var/www
    volumes:
      - ./php:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

volumes:
  db:
    driver: local